import { randomUUID } from 'node:crypto';

import { Router } from 'express';
import { z } from 'zod';
import { formatDate, monthLabel } from '@shared/dates.js';
import { formatMoney } from '@shared/money.js';

import { DEMO_ORGANISATION_ID } from '../config/tenant.js';
import { prisma } from '../db/prisma.js';
import { AppError } from '../lib/app-error.js';
import { requireAuth, requirePermission } from '../middleware/auth.js';
import { realtime } from '../realtime/events.js';
import { recordAudit } from '../services/audit.js';
import { checksumOf, renderDocument, type DocumentSpec } from '../services/demo-pdf.js';
import { notifyEmployee } from '../services/notifications.js';
import { isoDate } from '../services/payroll-inputs.js';

export const documentRouter = Router();

const idParam = z.object({ id: z.string().min(1) });
const DEMO_NOTICE =
  'Demo document — generated by PeoplePay360 for demonstration. Not a legal instrument and not issued by a real employer.';

const KINDS = ['EMPLOYMENT_LETTER', 'SALARY_CERTIFICATE', 'PAYSLIP'] as const;
type DocumentKind = (typeof KINDS)[number];

const generateSchema = z.object({
  kind: z.enum(KINDS),
  employeeId: z.string().min(1).optional(),
  payslipId: z.string().min(1).optional(),
});

const serialize = (document: {
  id: string;
  employeeId: string | null;
  contractId: string | null;
  category: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  visibility: string;
  uploadedAt: Date;
  uploadedById: string;
  acknowledgedAt: Date | null;
}) => ({
  ...document,
  uploadedAt: document.uploadedAt.toISOString(),
  acknowledgedAt: document.acknowledgedAt?.toISOString() ?? null,
});

/**
 * Build the document body from stored records.
 *
 * A salary certificate that quotes a number the payslip does not is worse than
 * no certificate, so every figure here comes from the same rows the payroll
 * engine used — never from a value the browser passed in.
 */
async function specFor(kind: DocumentKind, employeeId: string, payslipId?: string): Promise<DocumentSpec> {
  const employee = await prisma.employee.findUnique({
    where: { id: employeeId },
    include: {
      department: true,
      jobPosition: true,
      bank: true,
      contracts: { where: { status: 'ACTIVE' }, orderBy: { startDate: 'desc' }, take: 1 },
    },
  });
  if (!employee) throw new AppError('EMPLOYEE_NOT_FOUND', 404, 'Employee record not found.');
  const contract = employee.contracts[0];

  if (kind === 'PAYSLIP') {
    if (!payslipId) throw new AppError('PAYSLIP_REQUIRED', 400, 'Choose a payslip to generate.');
    const payslip = await prisma.payslip.findUnique({
      where: { id: payslipId },
      include: { lines: { orderBy: { sequence: 'asc' } }, payrun: true },
    });
    if (!payslip) throw new AppError('PAYSLIP_NOT_FOUND', 404, 'Payslip not found.');
    if (payslip.employeeId !== employeeId) {
      throw new AppError('PAYSLIP_MISMATCH', 409, 'That payslip belongs to a different employee.');
    }
    return {
      title: `Payslip — ${monthLabel(isoDate(payslip.periodStart))}`,
      subtitle: `${payslip.payrun.name} · ${formatDate(isoDate(payslip.periodStart))} to ${formatDate(isoDate(payslip.periodEnd))}`,
      reference: payslip.payslipRef,
      recipient: `${employee.fullName} · ${employee.employeeCode} · ${employee.jobPosition.title}, ${employee.department.name}`,
      sections: [
        {
          heading: 'Period inputs',
          rows: [
            { label: 'Expected working days', value: String(payslip.expectedDays) },
            { label: 'Worked days', value: Number(payslip.workedDays).toString() },
            { label: 'Paid leave days', value: Number(payslip.paidLeaveDays).toString() },
            { label: 'Unpaid leave days', value: Number(payslip.unpaidLeaveDays).toString() },
            { label: 'Overtime', value: `${Math.round(payslip.overtimeMinutes / 6) / 10} hours` },
            { label: 'Bank account', value: employee.bank?.accountNumberMasked ?? 'Not verified' },
          ],
        },
      ],
      lines: payslip.lines.map((line) => ({
        label: line.ruleName,
        detail: `${line.ruleCode} v${line.ruleVersion} · ${line.formulaSnapshot}`,
        amount: formatMoney(line.amount.toFixed(2)),
      })),
      totals: [
        { label: 'Gross', amount: formatMoney(payslip.gross.toFixed(2)) },
        { label: 'Total deductions', amount: formatMoney(payslip.totalDeductions.toFixed(2)) },
        { label: 'Net pay', amount: formatMoney(payslip.net.toFixed(2)) },
      ],
      footer: `${DEMO_NOTICE}\nEvery line above states the rule version and formula it came from; the stored input snapshot is the authority for this document.`,
    };
  }

  if (!contract) {
    throw new AppError(
      'NO_ACTIVE_CONTRACT',
      409,
      `${employee.fullName} has no active contract, so this document cannot state their terms.`,
      'Create or activate a contract first.',
    );
  }

  if (kind === 'SALARY_CERTIFICATE') {
    return {
      title: 'Salary certificate',
      subtitle: 'Statement of current contractual remuneration',
      reference: `SC-${employee.employeeCode}-${new Date().getFullYear()}`,
      recipient: `${employee.fullName} · ${employee.employeeCode}`,
      intro: `This certificate states the contractual remuneration recorded for ${employee.fullName} as at ${formatDate(isoDate(new Date()))}. It reflects contract ${contract.contractRef} and is generated directly from the payroll system of record.`,
      sections: [
        {
          heading: 'Employment',
          rows: [
            { label: 'Position', value: employee.jobPosition.title },
            { label: 'Department', value: employee.department.name },
            { label: 'Employment type', value: contract.employeeType.replace('_', ' ').toLowerCase() },
            { label: 'Joined', value: formatDate(isoDate(employee.joinDate)) },
            { label: 'Contract reference', value: contract.contractRef },
          ],
        },
        {
          heading: 'Remuneration',
          rows: [
            { label: 'Monthly gross wage', value: formatMoney(contract.wage.toFixed(2)) },
            { label: 'Annual gross wage', value: formatMoney(contract.wage.times(12).toFixed(2)) },
            { label: 'Effective from', value: formatDate(isoDate(contract.startDate)) },
          ],
        },
      ],
      footer: DEMO_NOTICE,
    };
  }

  return {
    title: 'Employment letter',
    subtitle: 'Confirmation of employment',
    reference: `EL-${employee.employeeCode}-${new Date().getFullYear()}`,
    recipient: `To whom it may concern`,
    intro: `This letter confirms that ${employee.fullName} (${employee.employeeCode}) is employed as ${employee.jobPosition.title} in the ${employee.department.name} department, and has been since ${formatDate(isoDate(employee.joinDate))}. Their current status is ${employee.status.toLowerCase()}.`,
    sections: [
      {
        heading: 'Details',
        rows: [
          { label: 'Full name', value: employee.fullName },
          { label: 'Employee code', value: employee.employeeCode },
          { label: 'Position', value: employee.jobPosition.title },
          { label: 'Department', value: employee.department.name },
          { label: 'Joined', value: formatDate(isoDate(employee.joinDate)) },
          { label: 'Contract reference', value: contract.contractRef },
        ],
      },
    ],
    footer: DEMO_NOTICE,
  };
}

/* ── generate ────────────────────────────────────────────────────────────── */

documentRouter.post('/documents/generate', requireAuth, async (request, response) => {
  const input = generateSchema.parse(request.body);
  const actor = request.currentUser!;
  const employeeId = actor.role === 'EMPLOYEE' ? actor.employeeId : (input.employeeId ?? actor.employeeId);
  if (!employeeId) throw new AppError('EMPLOYEE_REQUIRED', 400, 'Choose an employee for this document.');
  if (actor.role === 'EMPLOYEE' && input.employeeId && input.employeeId !== actor.employeeId) {
    throw new AppError('SELF_SCOPE_REQUIRED', 403, 'You can only generate your own documents.');
  }

  // The bytes are produced outside the transaction: PDF rendering is CPU work,
  // and holding a database transaction open across it would be wasteful.
  const spec = await specFor(input.kind, employeeId, input.payslipId);
  const bytes = await renderDocument(spec);
  const checksum = checksumOf(bytes);

  const created = await prisma.$transaction(async (tx) => {
    const documentId = `doc-${randomUUID()}`;
    const fileName = `${input.kind.toLowerCase()}-${employeeId}-${Date.now()}.pdf`;
    const document = await tx.document.create({
      data: {
        id: documentId,
        employeeId,
        category: input.kind === 'PAYSLIP' ? 'PAYSLIP' : 'LETTER',
        fileName,
        mimeType: 'application/pdf',
        sizeBytes: bytes.byteLength,
        visibility: 'SELF',
        uploadedAt: new Date(),
        uploadedById: actor.id,
      },
    });
    await tx.documentGeneration.create({
      data: {
        id: `dg-${randomUUID()}`,
        organisationId: DEMO_ORGANISATION_ID,
        documentId,
        kind: input.kind,
        employeeId,
        payslipId: input.payslipId ?? null,
        byteSize: bytes.byteLength,
        checksum,
        content: new Uint8Array(bytes),
        generatedById: actor.id,
      },
    });
    await recordAudit(tx, actor, {
      action: 'DOCUMENT_GENERATED',
      entityType: 'Document',
      entityId: documentId,
      summary: `${spec.title} generated for ${employeeId} (${bytes.byteLength} bytes, sha256 ${checksum.slice(0, 12)}).`,
      after: { kind: input.kind, fileName, checksum, byteSize: bytes.byteLength, demoDocument: true },
      correlationId: request.requestId,
    });
    await notifyEmployee(tx, employeeId, {
      kind: 'DOCUMENT_GENERATED',
      title: `${spec.title} is ready`,
      body: 'Demo document generation — the PDF is available in your documents.',
      entityType: 'Document',
      entityId: documentId,
    });
    return document;
  });

  realtime.publish({ type: 'document.updated', entityId: created.id, affectedEmployeeIds: [employeeId] });
  response.status(201).json({ data: { ...serialize(created), checksum, demoDocument: true } });
});

/* ── download ────────────────────────────────────────────────────────────── */

documentRouter.get('/documents/:id/download', requireAuth, async (request, response) => {
  const { id } = idParam.parse(request.params);
  const actor = request.currentUser!;
  const generation = await prisma.documentGeneration.findUnique({
    where: { documentId: id },
    include: { document: true },
  });
  if (!generation) {
    throw new AppError(
      'DOCUMENT_NOT_GENERATED',
      404,
      'There is no generated file for this document.',
      'Generate the document first.',
    );
  }
  // The permission check is here, not in the browser: a direct request for
  // somebody else's letter is refused whatever the interface offered.
  if (actor.role === 'EMPLOYEE' && generation.document.employeeId !== actor.employeeId) {
    throw new AppError('PERMISSION_DENIED', 403, 'This document belongs to another employee.');
  }

  response.locals.recordsRead = 1;
  response.setHeader('Content-Type', 'application/pdf');
  response.setHeader('Content-Length', String(generation.byteSize));
  response.setHeader('Content-Disposition', `attachment; filename="${generation.document.fileName}"`);
  response.setHeader('X-Document-Checksum', generation.checksum);
  response.send(Buffer.from(generation.content));
});

/* ── acknowledge ─────────────────────────────────────────────────────────── */

documentRouter.post('/documents/:id/acknowledge', requirePermission('document.read.self'), async (request, response) => {
  const { id } = idParam.parse(request.params);
  const actor = request.currentUser!;

  const document = await prisma.$transaction(async (tx) => {
    const current = await tx.document.findUnique({ where: { id } });
    if (!current) throw new AppError('DOCUMENT_NOT_FOUND', 404, 'Document not found.');
    if (actor.role === 'EMPLOYEE' && current.employeeId !== actor.employeeId) {
      throw new AppError('PERMISSION_DENIED', 403, 'This document belongs to another employee.');
    }
    if (current.acknowledgedAt) {
      throw new AppError('ALREADY_ACKNOWLEDGED', 409, 'This document is already acknowledged.');
    }
    const changed = await tx.document.updateMany({
      where: { id, acknowledgedAt: null },
      data: { acknowledgedAt: new Date() },
    });
    if (changed.count !== 1) {
      throw new AppError('ALREADY_ACKNOWLEDGED', 409, 'This document was acknowledged elsewhere.');
    }
    await recordAudit(tx, actor, {
      action: 'DOCUMENT_ACKNOWLEDGED',
      entityType: 'Document',
      entityId: id,
      summary: `${current.fileName} acknowledged by ${actor.displayName}.`,
      after: { acknowledgedAt: new Date().toISOString() },
      correlationId: request.requestId,
    });
    return tx.document.findUniqueOrThrow({ where: { id } });
  });

  realtime.publish({
    type: 'document.updated',
    entityId: id,
    affectedEmployeeIds: document.employeeId ? [document.employeeId] : [],
  });
  response.json({ data: serialize(document) });
});
